import Foundation

/// A single motivational quote shown on the Pomodoro break-over screen.
struct MotivationalQuote: Equatable, Identifiable {
    let id: Int
    let text: String
    let author: String
}

/// Offline corpus of inspirational quotes (verbatim text + author), collected
/// once from the Goodreads "inspirational" tag. Quotes are shown in their
/// original language regardless of the app's language setting.
/// See docs/superpowers/specs/2026-06-22-break-over-quote-design.md.
enum MotivationalQuotes {
    static let all: [MotivationalQuote] = [
        MotivationalQuote(id: 0, text: "You've gotta dance like there's nobody watching,\nLove like you'll never be hurt,\nSing like there's nobody listening,\nAnd live like it's heaven on earth.", author: "William W. Purkey"),
        MotivationalQuote(id: 1, text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi"),
        MotivationalQuote(id: 2, text: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.", author: "Martin Luther King Jr."),
        MotivationalQuote(id: 3, text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi"),
        MotivationalQuote(id: 4, text: "We accept the love we think we deserve.", author: "Stephen Chbosky"),
        MotivationalQuote(id: 5, text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche"),
        MotivationalQuote(id: 6, text: "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", author: "Marilyn Monroe"),
        MotivationalQuote(id: 7, text: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", author: "Albert Einstein"),
        MotivationalQuote(id: 8, text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde"),
        MotivationalQuote(id: 9, text: "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", author: "Neil Gaiman"),
        MotivationalQuote(id: 10, text: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane"),
        MotivationalQuote(id: 11, text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison"),
        MotivationalQuote(id: 12, text: "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.", author: "Elie Wiesel"),
        MotivationalQuote(id: 13, text: "It is never too late to be what you might have been.", author: "George Eliot"),
        MotivationalQuote(id: 14, text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou"),
        MotivationalQuote(id: 15, text: "Everything you can imagine is real.", author: "Pablo Picasso"),
        MotivationalQuote(id: 16, text: "You can never get a cup of tea large enough or a book long enough to suit me.", author: "C.S. Lewis"),
        MotivationalQuote(id: 17, text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw"),
        MotivationalQuote(id: 18, text: "To the well-organized mind, death is but the next great adventure.", author: "J.K. Rowling"),
        MotivationalQuote(id: 19, text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt"),
        MotivationalQuote(id: 20, text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston S. Churchill"),
        MotivationalQuote(id: 21, text: "So, this is my life. And I want you to know that I am both happy and sad and I'm still trying to figure out how that could be.", author: "Stephen Chbosky"),
        MotivationalQuote(id: 22, text: "Listen to the mustn'ts, child. Listen to the don'ts. Listen to the shouldn'ts, the impossibles, the won'ts. Listen to the never haves, then listen close to me... Anything can happen, child. Anything can be.", author: "Shel Silverstein"),
        MotivationalQuote(id: 23, text: "And, when you want something, all the universe conspires in helping you to achieve it.", author: "Paulo Coelho"),
        MotivationalQuote(id: 24, text: "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.", author: "John Lennon"),
        MotivationalQuote(id: 25, text: "It’s no use going back to yesterday, because I was a different person then.", author: "Lewis Carroll"),
        MotivationalQuote(id: 26, text: "It's the possibility of having a dream come true that makes life interesting.", author: "Paulo Coelho"),
        MotivationalQuote(id: 27, text: "What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it. Don't complain.", author: "Maya Angelou"),
        MotivationalQuote(id: 28, text: "A person's a person, no matter how small.", author: "Dr. Seuss"),
        MotivationalQuote(id: 29, text: "You can't live your life for other people. You've got to do what's right for you, even if it hurts some people you love.", author: "Nicholas Sparks"),
        MotivationalQuote(id: 30, text: "So we beat on, boats against the current, borne back ceaselessly into the past.", author: "F. Scott Fitzgerald"),
        MotivationalQuote(id: 31, text: "Well-behaved women seldom make history.", author: "Laurel Thatcher Ulrich"),
        MotivationalQuote(id: 32, text: "When I despair, I remember that all through history the way of truth and love have always won. There have been tyrants and murderers, and for a time, they can seem invincible, but in the end, they always fall. Think of it--always.", author: "Mahatma Gandhi"),
        MotivationalQuote(id: 33, text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn"),
        MotivationalQuote(id: 34, text: "Never doubt that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has.", author: "Margaret Mead"),
        MotivationalQuote(id: 35, text: "Do what you feel in your heart to be right – for you’ll be criticized anyway.", author: "Eleanor Roosevelt"),
        MotivationalQuote(id: 36, text: "I can't give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.", author: "Herbert Bayard Swope"),
        MotivationalQuote(id: 37, text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama XIV"),
        MotivationalQuote(id: 38, text: "Who controls the past controls the future. Who controls the present controls the past.", author: "George Orwell"),
        MotivationalQuote(id: 39, text: "Peace begins with a smile..", author: "Mother Teresa"),
        MotivationalQuote(id: 40, text: "I hope she'll be a fool -- that's the best thing a girl can be in this world, a beautiful little fool.", author: "F. Scott Fitzgerald"),
        MotivationalQuote(id: 41, text: "Friendship is unnecessary, like philosophy, like art.... It has no survival value; rather it is one of those things which give value to survival.", author: "C.S. Lewis"),
        MotivationalQuote(id: 42, text: "May you live every day of your life.", author: "Jonathan Swift"),
        MotivationalQuote(id: 43, text: "Whatever you are, be a good one.", author: "Abraham Lincoln"),
        MotivationalQuote(id: 44, text: "Attitude is a choice. Happiness is a choice. Optimism is a choice. Kindness is a choice. Giving is a choice. Respect is a choice. Whatever choice you make makes you. Choose wisely.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 45, text: "If my life is going to mean anything, I have to live it myself.", author: "Rick Riordan"),
        MotivationalQuote(id: 46, text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 47, text: "Two wrongs don't make a right, but they make a good excuse.", author: "Thomas Szasz"),
        MotivationalQuote(id: 48, text: "First they ignore you. Then they ridicule you. And then they attack you and want to burn you. And then they build monuments to you.", author: "Nicholas Klein"),
        MotivationalQuote(id: 49, text: "I believe that imagination is stronger than knowledge. That myth is more potent than history. That dreams are more powerful than facts. That hope always triumphs over experience. That laughter is the only cure for grief. And I believe that love is stronger than death.", author: "Robert Fulghum"),
        MotivationalQuote(id: 50, text: "Isn't it nice to think that tomorrow is a new day with no mistakes in it yet?", author: "L.M. Montgomery"),
        MotivationalQuote(id: 51, text: "You can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.", author: "A.A. Milne"),
        MotivationalQuote(id: 52, text: "Hope is the thing with feathers\nThat perches in the soul\nAnd sings the tune without the words\nAnd never stops at all.", author: "Emily Dickinson"),
        MotivationalQuote(id: 53, text: "Instead of worrying about what you cannot control, shift your energy to what you can create.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 54, text: "Hell is empty and all the devils are here.", author: "William Shakespeare"),
        MotivationalQuote(id: 55, text: "Talent hits a target no one else can hit. Genius hits a target no one else can see.", author: "Arthur Schopenhauer"),
        MotivationalQuote(id: 56, text: "Always do what you are afraid to do.", author: "Ralph Waldo Emerson"),
        MotivationalQuote(id: 57, text: "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down ‘happy’. They told me I didn’t understand the assignment, and I told them they didn’t understand life.", author: "John Lennon"),
        MotivationalQuote(id: 58, text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr."),
        MotivationalQuote(id: 59, text: "Be the reason someone smiles. Be the reason someone feels loved and believes in the goodness in people.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 60, text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr."),
        MotivationalQuote(id: 61, text: "Never let your sense of morals prevent you from doing what is right.", author: "Isaac Asimov"),
        MotivationalQuote(id: 62, text: "If you remember me, then I don't care if everyone else forgets.", author: "Haruki Murakami"),
        MotivationalQuote(id: 63, text: "Take responsibility of your own happiness, never put it in other people’s hands.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 64, text: "Accept yourself, love yourself, and keep moving forward. If you want to fly, you have to give up what weighs you down.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 65, text: "Waiting is painful. Forgetting is painful. But not knowing which to do is the worst kind of suffering.", author: "Paulo Coelho"),
        MotivationalQuote(id: 66, text: "Be mindful. Be grateful. Be positive. Be true. Be kind.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 67, text: "War is peace.\nFreedom is slavery.\nIgnorance is strength.", author: "George Orwell"),
        MotivationalQuote(id: 68, text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr."),
        MotivationalQuote(id: 69, text: "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 70, text: "I love to see a young girl go out and grab the world by the lapels. Life's a bitch. You've got to go out and kick ass.", author: "Maya Angelou"),
        MotivationalQuote(id: 71, text: "Turn your wounds into wisdom.", author: "Oprah Winfrey"),
        MotivationalQuote(id: 72, text: "Life is too short to waste your time on people who don’t respect, appreciate, and value you.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 73, text: "When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth.", author: "Arthur Conan Doyle"),
        MotivationalQuote(id: 74, text: "I do not fear death. I had been dead for billions and billions of years before I was born, and had not suffered the slightest inconvenience from it.", author: "Mark Twain"),
        MotivationalQuote(id: 75, text: "It isn't what you have or who you are or where you are or what you are doing that makes you happy or unhappy. It is what you think about it.", author: "Dale Carnegie"),
        MotivationalQuote(id: 76, text: "It’s only after you’ve stepped outside your comfort zone that you begin to change, grow, and transform.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 77, text: "I like living. I have sometimes been wildly, despairingly, acutely miserable, racked with sorrow; but through it all I still know quite certainly that just to be alive is a grand thing.", author: "Agatha Christie"),
        MotivationalQuote(id: 78, text: "You cannot control the behavior of others, but you can always choose how you respond to it.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 79, text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"),
        MotivationalQuote(id: 80, text: "He is half of my soul, as the poets say.", author: "Madeline Miller"),
        MotivationalQuote(id: 81, text: "I am not sure exactly what heaven will be like, but I know that when we die and it comes time for God to judge us, He will not ask, 'How many good things have you done in your life?' rather He will ask, 'How much love did you put into what you did?", author: "Mother Teresa"),
        MotivationalQuote(id: 82, text: "But I know, somehow, that only when it is dark enough can you see the stars.", author: "Martin Luther King Jr."),
        MotivationalQuote(id: 83, text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson"),
        MotivationalQuote(id: 84, text: "The past is a place of reference, not a place of residence; the past is a place of learning, not a place of living.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 85, text: "Life becomes easier and more beautiful when we can see the good in other people.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 86, text: "The truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, unless you realize that the situation is over, you cannot move forward.", author: "Steve Maraboli"),
        MotivationalQuote(id: 87, text: "Do what is right, not what is easy nor what is popular.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 88, text: "None but ourselves can free our minds.", author: "Bob Marley"),
        MotivationalQuote(id: 89, text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 90, text: "It is the time you have wasted for your rose that makes your rose so important.", author: "Antoine de Saint-Exupéry"),
        MotivationalQuote(id: 91, text: "If you want to be happy, do not dwell in the past, do not worry about the future, focus on living fully in the present.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 92, text: "People say nothing is impossible, but I do nothing every day.", author: "A.A. Milne"),
        MotivationalQuote(id: 93, text: "Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.", author: "Rabindranath Tagore"),
        MotivationalQuote(id: 94, text: "Pursue what catches your heart, not what catches your eyes.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 95, text: "Sometimes our light goes out, but is blown again into instant flame by an encounter with another human being.", author: "Albert Schweitzer"),
        MotivationalQuote(id: 96, text: "The things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy.", author: "Kalu Ndukwe Kalu"),
        MotivationalQuote(id: 97, text: "A painter should begin every canvas with a wash of black, because all things in nature are dark except where exposed by the light.", author: "Leonardo da Vinci"),
        MotivationalQuote(id: 98, text: "A woman's heart should be so hidden in God that a man has to seek Him just to find her.", author: "Max Lucado"),
        MotivationalQuote(id: 99, text: "Make improvements, not excuses. Seek respect, not attention.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 100, text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong"),
        MotivationalQuote(id: 101, text: "Don't be afraid of your fears. They're not there to scare you. They're there to let you know that something is worth it.", author: "C. JoyBell C."),
        MotivationalQuote(id: 102, text: "You never fail until you stop trying.", author: "Albert Einstein"),
        MotivationalQuote(id: 103, text: "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances, to choose one’s own way.", author: "Viktor E. Frankl"),
        MotivationalQuote(id: 104, text: "All the darkness in the world cannot extinguish the light of a single candle.", author: "St. Francis of Assisi"),
        MotivationalQuote(id: 105, text: "It's kind of fun to do the impossible.", author: "Walt Disney"),
        MotivationalQuote(id: 106, text: "Start each day with a positive thought and a grateful heart.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 107, text: "I was smiling yesterday,I am smiling today and I will smile tomorrow.Simply because life is too short to cry for anything.", author: "Santosh Kalwar"),
        MotivationalQuote(id: 108, text: "To see a World in a Grain of Sand\nAnd a Heaven in a Wild Flower,\nHold Infinity in the palm of your hand\nAnd Eternity in an hour.", author: "William Blake"),
        MotivationalQuote(id: 109, text: "Treat everyone with politeness and kindness, not because they are nice, but because you are.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 110, text: "Start writing, no matter what. The water does not flow until the faucet is turned on.", author: "Louis L'Amour"),
        MotivationalQuote(id: 111, text: "The Chinese use two brush strokes to write the word 'crisis.' One brush stroke stands for danger; the other for opportunity. In a crisis, be aware of the danger--but recognize the opportunity.", author: "John F. Kennedy"),
        MotivationalQuote(id: 112, text: "Stories never really end...even if the books like to pretend they do. Stories always go on. They don't end on the last page, any more than they begin on the first page.", author: "Cornelia Funke"),
        MotivationalQuote(id: 113, text: "Dance, when you're broken open. Dance, if you've torn the bandage off. Dance in the middle of the fighting. Dance in your blood. Dance when you're perfectly free.", author: "Rumi"),
        MotivationalQuote(id: 114, text: "If she's amazing, she won't be easy. If she's easy, she won't be amazing. If she's worth it, you wont give up. If you give up, you're not worthy. ... Truth is, everybody is going to hurt you; you just gotta find the ones worth suffering for.", author: "Bob Marley"),
        MotivationalQuote(id: 115, text: "The most beautiful things in the world cannot be seen or touched, they are felt with the heart.", author: "Antoine de Saint-Exupéry"),
        MotivationalQuote(id: 116, text: "Follow your heart, listen to your inner voice, stop caring about what others think.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 117, text: "No amount of regretting can change the past, and no amount of worrying can change the future.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 118, text: "Life is about accepting the challenges along the way, choosing to keep moving forward, and savoring the journey.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 119, text: "Once you have tasted flight, you will forever walk the earth with your eyes turned skyward, for there you have been, and there you will always long to return.", author: "Leonardo da Vinci"),
        MotivationalQuote(id: 120, text: "Don't say you don't have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein.", author: "H. Jackson Brown Jr."),
        MotivationalQuote(id: 121, text: "If you are irritated by every rub, how will your mirror be polished?", author: "Rumi"),
        MotivationalQuote(id: 122, text: "One love, one heart, one destiny.", author: "Bob Marley"),
        MotivationalQuote(id: 123, text: "You were born with wings, why prefer to crawl through life?", author: "Rumi"),
        MotivationalQuote(id: 124, text: "Any fool can be happy. It takes a man with real heart to make beauty out of the stuff that makes us weep.", author: "Clive Barker"),
        MotivationalQuote(id: 125, text: "So be sure when you step, Step with care and great tact. And remember that life's A Great Balancing Act. And will you succeed? Yes! You will, indeed! (98 and ¾ percent guaranteed) Kid, you'll move mountains.", author: "Dr. Seuss"),
        MotivationalQuote(id: 126, text: "The secret of health for both mind and body is not to mourn for the past, nor to worry about the future, but to live the present moment wisely and earnestly.", author: "Bukkyo Dendo Kyokai"),
        MotivationalQuote(id: 127, text: "What makes the desert beautiful,' said the little prince, 'is that somewhere it hides a well...", author: "Antoine de Saint-Exupéry"),
        MotivationalQuote(id: 128, text: "To me, Fearless is not the absense of fear. It's not being completely unafraid. To me, Fearless is having fears. Fearless is having doubts. Lots of them. To me, Fearless is living in spite of those things that scare you to death.", author: "Taylor Swift"),
        MotivationalQuote(id: 129, text: "Letting go means to come to the realization that some people are a part of your history, but not a part of your destiny.", author: "Steve Maraboli"),
        MotivationalQuote(id: 130, text: "Understanding is the first step to acceptance, and only with acceptance can there be recovery.", author: "J.K. Rowling"),
        MotivationalQuote(id: 131, text: "It's not the face, but the expressions on it. It's not the voice, but what you say. It's not how you look in that body, but the thing you do with it. You are beautiful.", author: "Stephenie Meyer"),
        MotivationalQuote(id: 132, text: "Never lose hope. Storms make people stronger and never last forever.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 133, text: "Great things happen to those who don't stop believing, trying, learning, and being grateful.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 134, text: "The past has no power over the present moment.", author: "Eckhart Tolle"),
        MotivationalQuote(id: 135, text: "‎Though nobody can go back and make a new beginning... Anyone can start over and make a new ending.", author: "Chico Xavier"),
        MotivationalQuote(id: 136, text: "Do not fear failure but rather fear not trying.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 137, text: "You see things; you say, 'Why?' But I dream things that never were; and I say 'Why not?", author: "George Bernard Shaw"),
        MotivationalQuote(id: 138, text: "We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the Universe. That makes us something very special.", author: "Stephen Hawking"),
        MotivationalQuote(id: 139, text: "Happiness [is] only real when shared", author: "Jon Krakauer"),
        MotivationalQuote(id: 140, text: "Live in the present, remember the past, and fear not the future, for it doesn't exist and never shall. There is only now.", author: "Christopher Paolini"),
        MotivationalQuote(id: 141, text: "‎Life is a shipwreck, but we must not forget to sing in the lifeboats.", author: "Voltaire"),
        MotivationalQuote(id: 142, text: "Is 'fat' really the worst thing a human being can be? Is 'fat' worse than 'vindictive', 'jealous', 'shallow', 'vain', 'boring' or 'cruel'? Not to me.", author: "J.K. Rowling"),
        MotivationalQuote(id: 143, text: "A ship is safe in harbor, but that's not what ships are for.", author: "John A. Shedd"),
        MotivationalQuote(id: 144, text: "Always find opportunities to make someone smile, and to offer random acts of kindness in everyday life.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 145, text: "When people don't express themselves, they die one piece at a time.", author: "Laurie Halse Anderson"),
        MotivationalQuote(id: 146, text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker"),
        MotivationalQuote(id: 147, text: "Maybe everyone can live beyond what they're capable of.", author: "Markus Zusak"),
        MotivationalQuote(id: 148, text: "Better to be strong than pretty and useless.", author: "Lilith Saintcrow"),
        MotivationalQuote(id: 149, text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
        MotivationalQuote(id: 150, text: "Even if you are on the right track, you’ll get run over if you just sit there.", author: "Will Rogers"),
        MotivationalQuote(id: 151, text: "May the forces of evil become confused on the way to your house.", author: "George Carlin"),
        MotivationalQuote(id: 152, text: "No matter what he does, every person on earth plays a central role in the history of the world. And normally he doesn't know it.", author: "Paulo Coelho"),
        MotivationalQuote(id: 153, text: "There was another life that I might have had, but I am having this one.", author: "Kazuo Ishiguro"),
        MotivationalQuote(id: 154, text: "There are some things you can't share without ending up liking each other, and knocking out a twelve-foot mountain troll is one of them.", author: "J.K. Rowling"),
        MotivationalQuote(id: 155, text: "Go on with what your heart tells you, or you will lose all.", author: "Rick Riordan"),
        MotivationalQuote(id: 156, text: "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.", author: "Eleanor Roosevelt"),
        MotivationalQuote(id: 157, text: "Nothing in the world is ever completely wrong. Even a stopped clock is right twice a day.", author: "Paulo Coelho"),
        MotivationalQuote(id: 158, text: "Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.", author: "Zig Ziglar"),
        MotivationalQuote(id: 159, text: "What's the good of living if you don't try a few things?", author: "Charles M. Schulz"),
        MotivationalQuote(id: 160, text: "You should never be surprised when someone treats you with respect, you should expect it.", author: "Sarah Dessen"),
        MotivationalQuote(id: 161, text: "Time doesn’t heal emotional pain, you need to learn how to let go.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 162, text: "All parents damage their children. It cannot be helped. Youth, like pristine glass, absorbs the prints of its handlers. Some parents smudge, others crack, a few shatter childhoods completely into jagged little pieces, beyond repair.", author: "Mitch Albom"),
        MotivationalQuote(id: 163, text: "Change will not come if we wait for some other person, or if we wait for some other time. We are the ones we've been waiting for. We are the change that we seek.", author: "Barack Obama"),
        MotivationalQuote(id: 164, text: "Every book, every volume you see here, has a soul. The soul of the person who wrote it and of those who read it and lived and dreamed with it. Every time a book changes hands, every time someone runs his eyes down its pages, its spirit grows and strengthens.", author: "Carlos Ruiz Zafón"),
        MotivationalQuote(id: 165, text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain"),
        MotivationalQuote(id: 166, text: "If people refuse to look at you in a new light and they can only see you for what you were, only see you for the mistakes you've made, if they don't realize that you are not your mistakes, then they have to go.", author: "Steve Maraboli"),
        MotivationalQuote(id: 167, text: "If you think you are too small to make a difference, try sleeping with a mosquito.", author: "Dalai Lama XIV"),
        MotivationalQuote(id: 168, text: "I don't think of all the misery, but of the beauty that still remains.", author: "Anne Frank"),
        MotivationalQuote(id: 169, text: "My concern is not whether God is on our side; my greatest concern is to be on God's side, for God is always right.", author: "Abraham Lincoln"),
        MotivationalQuote(id: 170, text: "Sometimes you have to lose all you have to find out who you truly are.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 171, text: "To shine your brightest light is to be who you truly are.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 172, text: "Reputation is what other people know about you. Honor is what you know about yourself.", author: "Lois McMaster Bujold"),
        MotivationalQuote(id: 173, text: "What do we live for, if it is not to make life less difficult for each other?", author: "George Eliot"),
        MotivationalQuote(id: 174, text: "Tears are words that need to be written.", author: "Paulo Coelho"),
        MotivationalQuote(id: 175, text: "Be thankful for everything that happens in your life; it’s all an experience.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 176, text: "I meant what I said and I said what I meant. An elephant's faithful one-hundred percent!", author: "Dr. Seuss"),
        MotivationalQuote(id: 177, text: "The important thing to you is not how many years in your life, but how much life in your years!", author: "Edward J. Stieglitz"),
        MotivationalQuote(id: 178, text: "Remember, darkness does not always equate to evil, just as light does not always bring good.", author: "P.C. Cast"),
        MotivationalQuote(id: 179, text: "I must be a mermaid, Rango. I have no fear of depths and a great fear of shallow living.", author: "Anaïs Nin"),
        MotivationalQuote(id: 180, text: "You never change your life until you step out of your comfort zone; change begins at the end of your comfort zone.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 181, text: "Let the improvement of yourself keep you so busy that you have no time to criticize others.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 182, text: "When I was about eight, I decided that the most wonderful thing, next to a human being, was a book.", author: "Margaret Walker"),
        MotivationalQuote(id: 183, text: "please believe that things are good with me, and even when they're not, they will be soon enough. And i will always believe the same about you.", author: "Stephen Chbosky"),
        MotivationalQuote(id: 184, text: "There must be those among whom we can sit down and weep and still be counted as warriors.", author: "Adrienne Rich"),
        MotivationalQuote(id: 185, text: "Never be bullied into silence. Never allow yourself to be made a victim. Accept no one's definition of your life, but define yourself.", author: "Harvey Fierstein"),
        MotivationalQuote(id: 186, text: "When one tugs at a single thing in nature, he finds it attached to the rest of the world.", author: "John Muir"),
        MotivationalQuote(id: 187, text: "Do not let the memories of your past limit the potential of your future. There are no limits to what you can achieve on your journey through life, except in your mind.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 188, text: "Stop comparing yourself to other people, just choose to be happy and live your own life.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 189, text: "Life before Death.\nStrength before Weakness.\nJourney before Destination.", author: "Brandon Sanderson"),
        MotivationalQuote(id: 190, text: "It is not the size of the dog in the fight that counts, but the fight in the dog that wins.", author: "Arthur G. Lewis"),
        MotivationalQuote(id: 191, text: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin"),
        MotivationalQuote(id: 192, text: "You are not rich until you have a rich heart.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 193, text: "Great heroes need great sorrows and burdens, or half their greatness goes unnoticed. It is all part of the fairy tale.", author: "Peter S. Beagle"),
        MotivationalQuote(id: 194, text: "Only people who are capable of loving strongly can also suffer great sorrow, but this same necessity of loving serves to counteract their grief and heals them.", author: "Leo Tolstoy"),
        MotivationalQuote(id: 195, text: "Anyone can hide. Facing up to things, working through them, that's what makes you strong.", author: "Sarah Dessen"),
        MotivationalQuote(id: 196, text: "I kept always two books in my pocket, one to read, one to write in.", author: "Robert Louis Stevenson"),
        MotivationalQuote(id: 197, text: "The question is not what you look at, but what you see.", author: "Henry David Thoreau"),
        MotivationalQuote(id: 198, text: "In the end\nthese things matter most:\nHow well did you love?\nHow fully did you live?\nHow deeply did you let go?", author: "Jack Kornfield"),
        MotivationalQuote(id: 199, text: "I'd rather be hated for who I am, than loved for who I am not.", author: "Kurt Cobain"),
        MotivationalQuote(id: 200, text: "Parents can only give good advice or put them on the right paths, but the final forming of a person's character lies in their own hands.", author: "Anne Frank"),
        MotivationalQuote(id: 201, text: "For me, I am driven by two main philosophies: know more today about the world than I knew yesterday and lessen the suffering of others. You'd be surprised how far that gets you.", author: "Neil deGrasse Tyson"),
        MotivationalQuote(id: 202, text: "Once you have read a book you care about, some part of it is always with you.", author: "Louis L'Amour"),
        MotivationalQuote(id: 203, text: "I wonder how many people don't get the one they want, but end up with the one they're supposed to be with.", author: "Fannie Flagg"),
        MotivationalQuote(id: 204, text: "Courage isn't having the strength to go on - it is going on when you don't have strength.", author: "Napoleon Bonaparte"),
        MotivationalQuote(id: 205, text: "Keep your face always toward the sunshine - and shadows will fall behind you.", author: "Walt Whitman"),
        MotivationalQuote(id: 206, text: "Wanting to be someone else is a waste of the person you are.", author: "Marilyn Monroe"),
        MotivationalQuote(id: 207, text: "Incredible change happens in your life when you decide to take control of what you do have power over instead of craving control over what you don't.", author: "Steve Maraboli"),
        MotivationalQuote(id: 208, text: "Shoot for the moon. Even if you miss, you'll land among the stars.", author: "Norman Vincent Peale"),
        MotivationalQuote(id: 209, text: "Trees that are slow to grow bear the best fruit.", author: "Molière"),
        MotivationalQuote(id: 210, text: "I want to be in a relationship where you telling me you love me is just a ceremonious validation of what you already show me.", author: "Steve Maraboli"),
        MotivationalQuote(id: 211, text: "All thinking men are atheists.", author: "Ernest Hemingway"),
        MotivationalQuote(id: 212, text: "The desire to reach for the stars is ambitious. The desire to reach hearts is wise.", author: "Maya Angelou"),
        MotivationalQuote(id: 213, text: "It is easy in the world to live after the world's opinion; it is easy in solitude to live after our own; but the great man is he who in the midst of the crowd keeps with perfect sweetness the independence of solitude.", author: "Ralph Waldo Emerson"),
        MotivationalQuote(id: 214, text: "Believe in your infinite potential. Your only limitations are those you set upon yourself.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 215, text: "However many holy words you read, however many you speak, what good will they do you if you do not act on upon them?", author: "Buddha"),
        MotivationalQuote(id: 216, text: "Do not set aside your happiness. Do not wait to be happy in the future. The best time to be happy is always now.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 217, text: "A concept is a brick. It can be used to build a courthouse of reason. Or it can be thrown through the window.", author: "Gilles Deleuze"),
        MotivationalQuote(id: 218, text: "Happiness is not the absence of problems, it's the ability to deal with them.", author: "Steve Maraboli"),
        MotivationalQuote(id: 219, text: "The higher we soar the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche"),
        MotivationalQuote(id: 220, text: "Ask for what you want and be prepared to get it!", author: "Maya Angelou"),
        MotivationalQuote(id: 221, text: "Imagination is everything. It is the preview of life's coming attractions.", author: "Albert Einstein"),
        MotivationalQuote(id: 222, text: "The starting point of all achievement is DESIRE. Keep this constantly in mind. Weak desire brings weak results, just as a small fire makes a small amount of heat.", author: "Napoleon Hill"),
        MotivationalQuote(id: 223, text: "We don’t need a list of rights and wrongs, tables of dos and don’ts: we need books, time, and silence. Thou shalt not is soon forgotten, but Once upon a time lasts forever.", author: "Philip Pullman"),
        MotivationalQuote(id: 224, text: "If you want to be happy, be.", author: "Leo Tolstoy"),
        MotivationalQuote(id: 225, text: "I just want you to know that you’re very special… and the only reason I’m telling you is that I don’t know if anyone else ever has.", author: "Stephen Chbosky"),
        MotivationalQuote(id: 226, text: "Help others without any reason and give without the expectation of receiving anything in return.", author: "Roy T. Bennett"),
        MotivationalQuote(id: 227, text: "Because,' she said, 'when you're scared but you still do it anyway, that's brave.", author: "Neil Gaiman"),
        MotivationalQuote(id: 228, text: "What's terrible is to pretend that second-rate is first-rate. To pretend that you don't need love when you do; or you like your work when you know quite well you're capable of better.", author: "Doris Lessing"),
        MotivationalQuote(id: 229, text: "Life has no remote....get up and change it yourself!", author: "Mark A. Cooper"),
        MotivationalQuote(id: 230, text: "The unhappiest people in this world, are those who care the most about what other people think.", author: "C. JoyBell C."),
        MotivationalQuote(id: 231, text: "When things break, it's not the actual breaking that prevents them from getting back together again. It's because a little piece gets lost - the two remaining ends couldn't fit together even if they wanted to. The whole shape has changed.", author: "John Green"),
        MotivationalQuote(id: 232, text: "If we have no peace, it is because we have forgotten that we belong to each other.", author: "Mother Teresa"),
        MotivationalQuote(id: 233, text: "If you don't go after what you want, you'll never have it. If you don't ask, the answer is always no. If you don't step forward, you're always in the same place.", author: "Nora Roberts"),
        MotivationalQuote(id: 234, text: "Stepping onto a brand-new path is difficult, but not more difficult than remaining in a situation, which is not nurturing to the whole woman.", author: "Maya Angelou"),
        MotivationalQuote(id: 235, text: "No matter how plain a woman may be, if truth and honesty are written across her face, she will be beautiful.", author: "Eleanor Roosevelt"),
        MotivationalQuote(id: 236, text: "Be steady and well-ordered in your life so that you can be fierce and original in your work.", author: "Gustave Flaubert"),
        MotivationalQuote(id: 237, text: "Whatever you can do or dream you can, begin it.\nBoldness has genius, power and magic in it!", author: "John Anster"),
    ]

    /// Returns a random quote, never the one whose id equals `excluding`
    /// (so the same line never repeats back-to-back when the list has >1 item).
    static func random(excluding: Int? = nil) -> MotivationalQuote {
        let pool = all.count > 1 ? all.filter { $0.id != excluding } : all
        return pool.randomElement() ?? all[0]
    }
}
